server:
  port: 2001

spring:
  application:
    name: seata-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: HAPPY,joker,123,
  cloud:
    nacos:
      discovery:
        namespace: "4246591e-4fd2-4c76-af47-09b470735a67"
        server-addr: localhost:8848

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml

seata:
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: SEATA_GROUP
      namespace: "4246591e-4fd2-4c76-af47-09b470735a67"
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      namespace: "4246591e-4fd2-4c76-af47-09b470735a67"
      username: nacos
      password: nacos
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    disable-global-transaction: false
    enable-degrade: false
  enabled: true
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: true
